# Generated by Django 5.2.3 on 2025-06-23 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("call", "0002_call_contact_number_note"),
        ("contact", "0002_alter_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contact.contact",
            ),
        ),
    ]
