# Generated by Django 5.2.3 on 2025-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("call", "0003_alter_call_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="caller_temp_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
