# Generated by Django 5.2.3 on 2025-06-25 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("call", "0004_call_caller_temp_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="call",
            name="caller_temp_id",
        ),
    ]
