# Generated by Django 5.2.3 on 2025-06-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("call", "0007_remove_call_caller_temp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="call_direction",
            field=models.CharField(
                blank=True,
                choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                max_length=255,
                null=True,
            ),
        ),
    ]
