# Generated by Django 5.2.3 on 2025-06-28 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("call", "0009_alter_call_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="call",
            options={"ordering": ["-updated_at"]},
        ),
    ]
