# Generated by Django 5.2.3 on 2025-06-23 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
